### PR TITLE
Script improvements

### PR DESCRIPTION
**Pull request by endrec**
Added
- handling of existing PRs
- possibility to use a file as the PR description

### CODE REVIEW

**Review by seanmcrw — APPROVED** [review]
LGTM

**Comment by jsgriffin** [comment]
Does this suggest we'll add merge instructions per repo?

**Comment by endrec** [comment]
Yes, that gives more flexibility than baking it in the docker image. Shall
I put a default in the image, and override it from the repo, if there is
one?

**Comment by jsgriffin** [comment]
Yeah, I think having a default is a good idea

**Comment by endrec** [comment]
> Yeah, I think having a default is a good idea

Okay, baked in instructions, and they can be overridden. 
See https://github.com/Rungway/playground/pull/18 comment edit history.

**Comment by endrec** [comment]
> Yeah, I think having a default is a good idea

Okay, baked in instructions, and they can be overridden.

**Comment by jsgriffin** [comment]
Looks good!

**Pull request merged**
